/* SPDX-License-Identifier: LGPL-2.1-or-later */
#pragma once

#include <stdint.h>

#define CFM_MAID_LENGTH 48

enum {
        IFLA_BRIDGE_CFM_UNSPEC,
        IFLA_BRIDGE_CFM_MEP_CREATE,
        IFLA_BRIDGE_CFM_MEP_DELETE,
        IFLA_BRIDGE_CFM_MEP_CONFIG,
        IFLA_BRIDGE_CFM_CC_CONFIG,
        IFLA_BRIDGE_CFM_CC_PEER_MEP_ADD,
        IFLA_BRIDGE_CFM_CC_PEER_MEP_REMOVE,
        IFLA_BRIDGE_CFM_CC_RDI,
        IFLA_BRIDGE_CFM_CC_CCM_TX,
        IFLA_BRIDGE_CFM_MEP_STATUS,
        IFLA_BRIDGE_CFM_CC_PEER_STATUS,
        __IFLA_BRIDGE_CFM_MAX,
};
#define IFLA_BRIDGE_CFM_MAX (__IFLA_BRIDGE_CFM_MAX - 1)

enum {
        IFLA_BRIDGE_CFM_MEP_CREATE_UNSPEC,
        IFLA_BRIDGE_CFM_MEP_CREATE_INSTANCE,
        IFLA_BRIDGE_CFM_MEP_CREATE_DOMAIN,
        IFLA_BRIDGE_CFM_MEP_CREATE_DIRECTION,
        IFLA_BRIDGE_CFM_MEP_CREATE_IFINDEX,
        __IFLA_BRIDGE_CFM_MEP_CREATE_MAX,
};
#define IFLA_BRIDGE_CFM_MEP_CREATE_MAX (__IFLA_BRIDGE_CFM_MEP_CREATE_MAX - 1)

enum {
        IFLA_BRIDGE_CFM_MEP_DELETE_UNSPEC,
        IFLA_BRIDGE_CFM_MEP_DELETE_INSTANCE,
        __IFLA_BRIDGE_CFM_MEP_DELETE_MAX,
};
#define IFLA_BRIDGE_CFM_MEP_DELETE_MAX (__IFLA_BRIDGE_CFM_MEP_DELETE_MAX - 1)

enum {
        IFLA_BRIDGE_CFM_MEP_CONFIG_UNSPEC,
        IFLA_BRIDGE_CFM_MEP_CONFIG_INSTANCE,
        IFLA_BRIDGE_CFM_MEP_CONFIG_UNICAST_MAC,
        IFLA_BRIDGE_CFM_MEP_CONFIG_MDLEVEL,
        IFLA_BRIDGE_CFM_MEP_CONFIG_MEPID,
        __IFLA_BRIDGE_CFM_MEP_CONFIG_MAX,
};
#define IFLA_BRIDGE_CFM_MEP_CONFIG_MAX (__IFLA_BRIDGE_CFM_MEP_CONFIG_MAX - 1)

enum {
        IFLA_BRIDGE_CFM_CC_CONFIG_UNSPEC,
        IFLA_BRIDGE_CFM_CC_CONFIG_INSTANCE,
        IFLA_BRIDGE_CFM_CC_CONFIG_ENABLE,
        IFLA_BRIDGE_CFM_CC_CONFIG_EXP_INTERVAL,
        IFLA_BRIDGE_CFM_CC_CONFIG_EXP_MAID,
        __IFLA_BRIDGE_CFM_CC_CONFIG_MAX,
};
#define IFLA_BRIDGE_CFM_CC_CONFIG_MAX (__IFLA_BRIDGE_CFM_CC_CONFIG_MAX - 1)

enum {
        IFLA_BRIDGE_CFM_CC_PEER_MEP_UNSPEC,
        IFLA_BRIDGE_CFM_CC_PEER_MEP_INSTANCE,
        IFLA_BRIDGE_CFM_CC_PEER_MEPID,
        __IFLA_BRIDGE_CFM_CC_PEER_MEP_MAX,
};
#define IFLA_BRIDGE_CFM_CC_PEER_MEP_MAX (__IFLA_BRIDGE_CFM_CC_PEER_MEP_MAX - 1)

enum {
        IFLA_BRIDGE_CFM_CC_RDI_UNSPEC,
        IFLA_BRIDGE_CFM_CC_RDI_INSTANCE,
        IFLA_BRIDGE_CFM_CC_RDI_RDI,
        __IFLA_BRIDGE_CFM_CC_RDI_MAX,
};
#define IFLA_BRIDGE_CFM_CC_RDI_MAX (__IFLA_BRIDGE_CFM_CC_RDI_MAX - 1)

enum {
        IFLA_BRIDGE_CFM_CC_CCM_TX_UNSPEC,
        IFLA_BRIDGE_CFM_CC_CCM_TX_INSTANCE,
        IFLA_BRIDGE_CFM_CC_CCM_TX_DMAC,
        IFLA_BRIDGE_CFM_CC_CCM_TX_SEQ_NO_UPDATE,
        IFLA_BRIDGE_CFM_CC_CCM_TX_PERIOD,
        IFLA_BRIDGE_CFM_CC_CCM_TX_IF_TLV,
        IFLA_BRIDGE_CFM_CC_CCM_TX_IF_TLV_VALUE,
        IFLA_BRIDGE_CFM_CC_CCM_TX_PORT_TLV,
        IFLA_BRIDGE_CFM_CC_CCM_TX_PORT_TLV_VALUE,
        __IFLA_BRIDGE_CFM_CC_CCM_TX_MAX,
};
#define IFLA_BRIDGE_CFM_CC_CCM_TX_MAX (__IFLA_BRIDGE_CFM_CC_CCM_TX_MAX - 1)

enum {
        IFLA_BRIDGE_CFM_MEP_STATUS_UNSPEC,
        IFLA_BRIDGE_CFM_MEP_STATUS_INSTANCE,
        IFLA_BRIDGE_CFM_MEP_STATUS_OPCODE_UNEXP_SEEN,
        IFLA_BRIDGE_CFM_MEP_STATUS_VERSION_UNEXP_SEEN,
        IFLA_BRIDGE_CFM_MEP_STATUS_RX_LEVEL_LOW_SEEN,
        __IFLA_BRIDGE_CFM_MEP_STATUS_MAX,
};
#define IFLA_BRIDGE_CFM_MEP_STATUS_MAX (__IFLA_BRIDGE_CFM_MEP_STATUS_MAX - 1)

enum {
        IFLA_BRIDGE_CFM_CC_PEER_STATUS_UNSPEC,
        IFLA_BRIDGE_CFM_CC_PEER_STATUS_INSTANCE,
        IFLA_BRIDGE_CFM_CC_PEER_STATUS_PEER_MEPID,
        IFLA_BRIDGE_CFM_CC_PEER_STATUS_CCM_DEFECT,
        IFLA_BRIDGE_CFM_CC_PEER_STATUS_RDI,
        IFLA_BRIDGE_CFM_CC_PEER_STATUS_PORT_TLV_VALUE,
        IFLA_BRIDGE_CFM_CC_PEER_STATUS_IF_TLV_VALUE,
        IFLA_BRIDGE_CFM_CC_PEER_STATUS_SEEN,
        IFLA_BRIDGE_CFM_CC_PEER_STATUS_TLV_SEEN,
        IFLA_BRIDGE_CFM_CC_PEER_STATUS_SEQ_UNEXP_SEEN,
        __IFLA_BRIDGE_CFM_CC_PEER_STATUS_MAX,
};
#define IFLA_BRIDGE_CFM_CC_PEER_STATUS_MAX (__IFLA_BRIDGE_CFM_CC_PEER_STATUS_MAX - 1)
