/* SPDX-License-Identifier: LGPL-2.1-or-later */
#pragma once

#include <stdint.h>
#include <linux/if_ether.h>

#ifndef AF_BRIDGE
#define AF_BRIDGE 7
#endif

struct ifla_bridge_id {
    uint8_t prio[2];
    uint8_t addr[6];
};

struct br_port_msg {
    uint8_t  family;
    uint32_t ifindex;
};

struct br_boolopt_multi {
    uint32_t optval;
    uint32_t optmask;
};

#define BRCTL_GET_VERSION     1
#define BRCTL_GET_BRIDGES     2
#define BRCTL_ADD_BRIDGE      3
#define BRCTL_DEL_BRIDGE      4
#define BRCTL_ADD_IF          5
#define BRCTL_DEL_IF          6
#define BRCTL_GET_BRIDGE_INFO 7

enum {
    IFLA_BR_UNSPEC,
    IFLA_BR_FORWARD_DELAY,
    IFLA_BR_HELLO_TIME,
    IFLA_BR_MAX_AGE,
    IFLA_BR_AGEING_TIME,
    IFLA_BR_STP_STATE,
    IFLA_BR_PRIORITY,
    IFLA_BR_VLAN_FILTERING,
    IFLA_BR_VLAN_PROTOCOL,
    IFLA_BR_GROUP_FWD_MASK,
    IFLA_BR_ROOT_ID,
    IFLA_BR_BRIDGE_ID,
    IFLA_BR_ROOT_PORT,
    IFLA_BR_ROOT_PATH_COST,
    IFLA_BR_TOPOLOGY_CHANGE,
    IFLA_BR_TOPOLOGY_CHANGE_DETECTED,
    IFLA_BR_HELLO_TIMER,
    IFLA_BR_TCN_TIMER,
    IFLA_BR_TOPOLOGY_CHANGE_TIMER,
    IFLA_BR_GC_TIMER,
    IFLA_BR_GROUP_ADDR,
    IFLA_BR_FDB_FLUSH,
    IFLA_BR_MCAST_ROUTER,
    IFLA_BR_MCAST_SNOOPING,
    IFLA_BR_MCAST_QUERY_USE_IFADDR,
    IFLA_BR_MCAST_QUERIER,
    IFLA_BR_MCAST_HASH_ELASTICITY,
    IFLA_BR_MCAST_HASH_MAX,
    IFLA_BR_MCAST_LAST_MEMBER_CNT,
    IFLA_BR_MCAST_STARTUP_QUERY_CNT,
    IFLA_BR_MCAST_LAST_MEMBER_INTVL,
    IFLA_BR_MCAST_MEMBERSHIP_INTVL,
    IFLA_BR_MCAST_QUERIER_INTVL,
    IFLA_BR_MCAST_QUERY_INTVL,
    IFLA_BR_MCAST_QUERY_RESPONSE_INTVL,
    IFLA_BR_MCAST_STARTUP_QUERY_INTVL,
    IFLA_BR_NF_CALL_IPTABLES,
    IFLA_BR_NF_CALL_IP6TABLES,
    IFLA_BR_NF_CALL_ARPTABLES,
    IFLA_BR_VLAN_DEFAULT_PVID,
    IFLA_BR_VLAN_STATS_ENABLED,
    IFLA_BR_MCAST_STATS_ENABLED,
    IFLA_BR_MCAST_IGMP_VERSION,
    IFLA_BR_MCAST_MLD_VERSION,
    IFLA_BR_VLAN_STATS_PER_PORT,
    IFLA_BR_MULTI_BOOLOPT,
    IFLA_BR_FDB_N_LEARNED,
    IFLA_BR_FDB_MAX_LEARNED,
    __IFLA_BR_MAX,
};
#define IFLA_BR_MAX (__IFLA_BR_MAX - 1)

/* Bridge port states. */
#define BR_STATE_DISABLED   0
#define BR_STATE_LISTENING  1
#define BR_STATE_LEARNING   2
#define BR_STATE_FORWARDING 3
#define BR_STATE_BLOCKING   4
